#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-{{ .Values.branch }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.externalHostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.name }}-{{ .Values.branch }}
            port:
              number: 80
        path: /{{ .Values.branch }}/maven-repo/{{ .Values.ingress.pathSuffix }}
        pathType: Prefix
{{- end }}
